# Generated by Django 4.2.30 on 2026-07-08 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientUmbrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Ingredient Umbrellas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('brand', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('product_type', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('exfoliant', 'Exfoliant'), ('mask', 'Mask'), ('eye_cream', 'Eye Cream'), ('oil', 'Oil'), ('treatment', 'Treatment'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('avg_ph', models.FloatField(blank=True, help_text='Average pH level of the product', null=True)),
                ('raw_inci', models.JSONField(blank=True, default=list, help_text='Full ordered INCI ingredient list as scraped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('affiliate_network', models.CharField(choices=[('sovrn', 'Sovrn'), ('amazon_associates', 'Amazon Associates'), ('direct', 'Direct / None')], default='sovrn', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Routine', max_length=200)),
                ('time_of_day', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening'), ('BOTH', 'Both')], default='AM', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='User-facing label, e.g. "Visible Redness"', max_length=200, unique=True)),
                ('internal_key', models.SlugField(help_text='Internal key for backend logic, e.g. "rosacea"', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Skin Concern',
                'verbose_name_plural': 'Skin Concerns',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], default='', max_length=20)),
                ('skin_concerns', models.ManyToManyField(blank=True, help_text='Skin concerns the user has identified', related_name='users', to='api.skinconcern')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='RetailerListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('product_url', models.URLField(max_length=1000)),
                ('affiliate_url', models.URLField(blank=True, default='', help_text='Sovrn/affiliate-wrapped URL', max_length=1000)),
                ('in_stock', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_listings', to='api.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.retailer')),
            ],
            options={
                'verbose_name': 'Retailer Listing',
                'verbose_name_plural': 'Retailer Listings',
                'ordering': ['price'],
                'unique_together': {('product', 'retailer')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='concerns',
            field=models.ManyToManyField(blank=True, help_text='Skin concerns this product addresses', related_name='products', to='api.skinconcern'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inci_name', models.CharField(help_text='Canonical INCI name, e.g. Retinol', max_length=300, unique=True)),
                ('common_name', models.CharField(blank=True, default='', help_text='User-friendly common name', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('science_summary', models.TextField(blank=True, default='', help_text='Summary of peer-reviewed evidence')),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='List of alternate names for synonym resolution')),
                ('concerns_supported', models.ManyToManyField(blank=True, help_text='Skin concerns this ingredient helps address', related_name='supporting_ingredients', to='api.skinconcern')),
                ('umbrellas', models.ManyToManyField(blank=True, help_text='Umbrella categories this ingredient belongs to', related_name='ingredients', to='api.ingredientumbrella')),
            ],
            options={
                'ordering': ['inci_name'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page', models.CharField(blank=True, default='', help_text='Page URL where the click originated', max_length=500)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='api.product')),
                ('retailer_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='api.retailerlisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Click Event',
                'verbose_name_plural': 'Click Events',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source', models.CharField(blank=True, default='', help_text='e.g. PubMed, Journal of Dermatology', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.ManyToManyField(blank=True, help_text='Ingredients discussed in this article', related_name='articles', to='api.ingredient')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_items', to='api.product')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.routine')),
            ],
            options={
                'verbose_name': 'Routine Item',
                'verbose_name_plural': 'Routine Items',
                'ordering': ['step_order'],
                'unique_together': {('routine', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position in INCI list (1 = highest concentration)')),
                ('concentration', models.CharField(blank=True, default='', help_text='Optional concentration, e.g. "2%"', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='api.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='api.product')),
            ],
            options={
                'verbose_name': 'Product Ingredient',
                'verbose_name_plural': 'Product Ingredients',
                'ordering': ['order'],
                'unique_together': {('product', 'ingredient')},
            },
        ),
    ]
