# Generated by Django 4.2.30 on 2026-07-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(blank=True, help_text='Number of reviews (e.g. 1488)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_rating',
            field=models.FloatField(blank=True, help_text='Average review rating (e.g. 4.8)', null=True),
        ),
    ]
