# Generated by Django 4.2.30 on 2026-07-27 21:27

from django.db import migrations, models
import django.db.models.deletion


def copy_m2m_to_through(apps, schema_editor):
    """Copy existing concerns_supported M2M rows into IngredientConcernEvidence."""
    IngredientConcernEvidence = apps.get_model('api', 'IngredientConcernEvidence')
    # The old M2M table is api_ingredient_concerns_supported
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'SELECT ingredient_id, skinconcern_id FROM api_ingredient_concerns_supported'
        )
        rows = cursor.fetchall()
    for ingredient_id, concern_id in rows:
        IngredientConcernEvidence.objects.using(db_alias).get_or_create(
            ingredient_id=ingredient_id,
            concern_id=concern_id,
            defaults={'evidence_tier': 'prospective', 'pubmed_count': 0},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_review_count_product_review_rating'),
    ]

    operations = [
        # 1. Add new JSON fields to Ingredient and SkinConcern
        migrations.AddField(
            model_name='ingredient',
            name='pubmed_terms',
            field=models.JSONField(blank=True, default=list, help_text='PubMed search fragments, e.g. [{"term": "Caffeine", "field": "Mesh"}, {"term": "caffeine", "field": "tiab"}]'),
        ),
        migrations.AddField(
            model_name='skinconcern',
            name='pubmed_excluders',
            field=models.JSONField(blank=True, default=list, help_text='PubMed exclusion terms, e.g. [{"term": "Alopecia", "field": "Mesh"}, {"term": "hair", "field": "tiab"}]'),
        ),
        migrations.AddField(
            model_name='skinconcern',
            name='pubmed_terms',
            field=models.JSONField(blank=True, default=list, help_text='PubMed search terms, e.g. [{"term": "Skin Aging", "field": "Mesh"}, {"term": "photoaging", "field": "tiab"}]'),
        ),
        # 2. Create the through model table
        migrations.CreateModel(
            name='IngredientConcernEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_count', models.IntegerField(default=0)),
                ('evidence_tier', models.CharField(choices=[('well_founded', 'Well Founded'), ('studied', 'Studied'), ('prospective', 'Prospective')], default='prospective', max_length=20)),
                ('query_used', models.TextField(blank=True, default='', help_text='Stored PubMed query string for debugging/auditing')),
                ('last_queried', models.DateTimeField(blank=True, null=True)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_scores', to='api.skinconcern')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_scores', to='api.ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient-Concern Evidence',
                'verbose_name_plural': 'Ingredient-Concern Evidence',
                'unique_together': {('ingredient', 'concern')},
            },
        ),
        # 3. Copy existing M2M data into the through table
        migrations.RunPython(copy_m2m_to_through, migrations.RunPython.noop),
        # 4. Remove the old auto-generated M2M field
        migrations.RemoveField(
            model_name='ingredient',
            name='concerns_supported',
        ),
        # 5. Re-add it with the through model
        migrations.AddField(
            model_name='ingredient',
            name='concerns_supported',
            field=models.ManyToManyField(
                blank=True,
                related_name='supporting_ingredients',
                through='api.IngredientConcernEvidence',
                to='api.skinconcern',
            ),
        ),
    ]
