# Generated by Django 4.2.30 on 2026-07-27 22:09

from django.db import migrations, models
import django.db.models.deletion


# ── Taxonomy seed data ──────────────────────────────────────────────────────
# Each parent maps to a list of (internal_key, label) sub-concerns.
# Existing concerns are matched by internal_key and re-parented.

TAXONOMY = {
    ('anti-aging', 'Anti-Aging'): [
        ('fine-lines', 'Fine Lines & Wrinkles'),
        ('skin-firmness', 'Skin Firmness & Elasticity'),
        ('photoaging', 'Photoaging'),
    ],
    ('acne-blemishes', 'Acne & Blemishes'): [
        ('acne', 'Blemish-Prone Skin'),          # existing
        ('pores', 'Clogged Pores'),              # existing
        ('excess-sebum', 'Excess Sebum'),
    ],
    ('hydration-barrier', 'Hydration & Barrier'): [
        ('dryness', 'Severe Dryness'),           # existing
        ('barrier-repair', 'Barrier Repair'),
        ('tewl', 'Transepidermal Water Loss'),
    ],
    ('pigmentation-tone', 'Pigmentation & Tone'): [
        ('pigmentation', 'Uneven Skin Tone'),    # existing
        ('dark-spots', 'Dark Spots'),
        ('melasma', 'Melasma'),
    ],
    ('sensitivity-redness', 'Sensitivity & Redness'): [
        ('redness', 'Easily Irritated Skin'),    # existing
        ('rosacea', 'Rosacea'),
        ('post-procedure', 'Post-Procedure Recovery'),
    ],
    ('sun-protection', 'Sun Protection'): [
        ('uv-defense', 'UV Defense'),
        ('photodamage-prevention', 'Photodamage Prevention'),
    ],
}


def seed_taxonomy(apps, schema_editor):
    SkinConcern = apps.get_model('api', 'SkinConcern')

    for (parent_key, parent_label), children in TAXONOMY.items():
        parent, _ = SkinConcern.objects.get_or_create(
            internal_key=parent_key,
            defaults={'label': parent_label},
        )
        # Ensure parent has no parent itself
        parent.parent = None
        parent.save()

        for child_key, child_label in children:
            child, created = SkinConcern.objects.get_or_create(
                internal_key=child_key,
                defaults={'label': child_label},
            )
            child.parent = parent
            child.save()


def reverse_taxonomy(apps, schema_editor):
    SkinConcern = apps.get_model('api', 'SkinConcern')
    # Just clear parent references; don't delete anything
    SkinConcern.objects.all().update(parent=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pubmed_evidence_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinconcern',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent concern for sub-concern hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.skinconcern'),
        ),
        migrations.RunPython(seed_taxonomy, reverse_taxonomy),
    ]

