# Generated by Django 4.2.30 on 2026-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_concern_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientconcernevidence',
            name='top_articles',
            field=models.JSONField(blank=True, default=list, help_text='Top PubMed articles, e.g. [{"pmid": "12345", "title": "...", "year": "2023"}]'),
        ),
    ]
