# Generated by Django 4.2.30 on 2026-08-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_evidence_top_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ph_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', help_text='Confidence level of the pH estimate: high, medium, or low', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, choices=[('ultra_gentle', 'Ultra-Gentle'), ('gentle', 'Gentle'), ('moderate', 'Moderate'), ('potent', 'Potent'), ('clinical', 'Clinical')], db_index=True, default='', help_text='Estimated product potency tier', max_length=20),
        ),
    ]
